version: "3.1"

services:
    node:
        image: node:latest
        volumes:
            - .:/application
        ports:
            - '4000:4000'
        working_dir: '/application'
        command: 'npm run dev'
